### ISSUE TITLE
Chapter 1: Richard Cook's [11] link is now broken

### ISSUE THREAD

**Issue by rnsanchez** [ept/ddia-references#11]
While trying to follow [11], I've found a broken link.  I did find some alternatives to the original/intended PDF:

* http://web.archive.org/web/20200512193009/http://web.mit.edu/2.75/resources/random/How%20Complex%20Systems%20Fail.pdf (most likely as permanent as Web Archive itself; though revision "D")
* https://www.researchgate.net/publication/228797158_How_complex_systems_fail (as far as I can tell, offered by the author but with ResearchGate letterhead; revision "G")
* https://how.complexsystems.fail/

Unfortunately, I don't know which one to suggest.

**Comment by ept** [comment]
This one seems good to me: https://www.adaptivecapacitylabs.com/HowComplexSystemsFail.pdf (from the website of the company that the author co-founded)
