### ISSUE TITLE
Chapter 1: Reference [19] is broken; Dynamo

### ISSUE THREAD

**Issue by gurrpi** [ept/ddia-references#17]
The link gives error message `This XML file does not appear to have any style information associated with it. The document tree is shown below.` for link:
Giuseppe DeCandia, Deniz Hastorun, Madan Jampani, et al.: “Dynamo: Amazon's Highly Available Key-Value Store,” at 21st ACM Symposium on Operating Systems Principles (SOSP), October 2007.: https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf

Full error message:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>TCJVJPGK29CHX79A</RequestId>
<HostId>
kpQKZdP6eFKrL0FYPg8/yuCpC1ym0G6di4eJW3ZWTKzWdt5arPNKn9FSjVngUgHX2FUHmmnvHpU=
</HostId>
</Error>
```

**Comment by gurrpi** [comment]
I found working link: https://sites.cs.ucsb.edu/~agrawal/fall2009/dynamo.pdf

**Comment by ept** [comment]
The original URL seems to be working again now.
