### ISSUE TITLE
Chapter 1 - Broken link

### ISSUE THREAD

**Issue by saurav-2104** [ept/ddia-references#3]
The link which represents the following in Chapter 1 gives a 404.

Walter L. Heimerdinger and Charles B. Weinstock: “A Conceptual Framework for System Fault Tolerance,” Technical Report CMU/SEI-92-TR-033, Software Engineering Institute, Carnegie Mellon University, October 1992.

**Comment by anrub** [comment]
see https://github.com/ept/ddia-references/pull/2
